### ISSUE TITLE
User should be in Reframe DB and not tracked as a separate Reagent atom

### ISSUE THREAD

**Issue by trycatcher** [nilenso/time-tracker-web-nxt#9]
Wrt 
https://github.com/nilenso/time-tracker-web-nxt/blob/master/src/cljs/time_tracker_web_nxt/auth.cljs
and
https://github.com/nilenso/time-tracker-web-nxt/blob/log-time/src/cljs/time_tracker_web_nxt/views.cljs

**Comment by trycatcher** [comment]
User is in Reframe DB and that is being used to render views conditionally when User signs in. We want to eliminate the Reagent atom if possible

**Comment by kirang89** [comment]
Fixed hence closing.
